Feature: Add scroll behaviour when closing modal
flekschas/svelte-simple-modal pull request #97
Opened 2023-01-26 11:51 UTC by FluffyDiscord

## Background

I am using this package for rendering forms in modal and it has currently one annoying issue with forced smooth scroll.

## Currently Observed Behavior

I am observing forced smooth scroll in Google Chrome (tested only there) when package scrolls back the page to previous saved position after modal is closed.

## New Behavior

Added option to customize `window.scrollTo()` scroll behavior that can overwrite/force it.

2023-01-26 15:10 UTC, flekschas commented
Thanks for the PR. Could you provide a video or a demo of the forced smooth scroll in Chrome?

2023-01-26 15:12 UTC, flekschas requested changes

2023-01-26 15:12 UTC, flekschas commented on src/Modal.svelte
> +   * @type {"instant" | "smooth"}
What about 
```suggestion
   * @type {'instant' | 'smooth' | 'auto'}
```

According to https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo, `auto` is the default value.

2023-01-26 15:12 UTC, flekschas commented on src/Modal.svelte
> +  export let scrollBehaviour = undefined;
Invalid type. I think it'd be better to set it to `auto`.

```suggestion
  export let scrollBehaviour = 'auto';
```

2023-01-26 18:54 UTC, flekschas commented
Awesome! Thanks for clarifying.

The code looks good but what I am still debating is why one would use a `smooth` scroll behavior? I am tempted to fix it to `instant` for simplicity. Any thoughts?

2023-01-27 07:05 UTC, FluffyDiscord commented
Well I agree that it does not make sense to use anything besides `instant`. I just made it to be backwards compatible I guess.

This **can** be considered as a bug.

Should I change this PR into forcing `instant`?

2023-01-27 13:08 UTC, flekschas commented
I appreciate the effort and consideration to make this a backward compatible PR but I think we can just treat the current behavior as a bug and enforce instant scrolling. Do you mind adjusting this PR accordingly? Thanks!
On Jan 27, 2023 at 2:06 AM -0500, Mossshine ***@***.***>, wrote:
> Well I agree that it does not make sense to use anything besides instant. I just made it to be backwards compatible I guess.
> This can be considered as a bug.
> Should I change this PR into forcing instant?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

2023-01-27 16:30 UTC, merged